"""
nexus-npm-package-ws-has-241560546-weekly-down — LangChain Tool Wrappers
Generated by NEXUS v6.0. Talks real MCP protocol via _mcp_client.py.

Usage:
    from sdk_wrappers.langchain_tool import open_websocket_session_tool, send_typed_ws_frame_tool, drain_ws_frame_buffer_tool, inspect_ws_session_telemetry_tool, close_websocket_session_tool
    agent = initialize_agent([open_websocket_session_tool, send_typed_ws_frame_tool, drain_ws_frame_buffer_tool, inspect_ws_session_telemetry_tool, close_websocket_session_tool], llm,
                              agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION)
"""

from typing import Any
from langchain_core.tools import StructuredTool
from pydantic import BaseModel, Field

from ._mcp_client import call_mcp_tool

class OpenWebsocketSessionInput(BaseModel):
    target_url: str = Field(..., description='Full WebSocket URL to connect to (must start with ws:// or wss://). Example: wss://stream.example.com/feed')
    headers: list[str] = Field(None, description="Optional HTTP headers to send on handshake, formatted as 'Key: Value' strings. Use for Authorization, Sec-WebSocket-Protocol, or custom headers.")
    frame_schema_json: str = Field(None, description='Optional JSON Schema (as a JSON string) describing expected frame payloads. Used to baseline entropy scoring. If omitted, entropy is computed against empirical baseline from first 10 frames.')
    connect_timeout_ms: float = Field(None, description='Maximum milliseconds to wait for the WebSocket handshake to complete before returning an error.')


def _open_websocket_session_impl(target_url, headers, frame_schema_json, connect_timeout_ms) -> Any:
    return call_mcp_tool("nexus_npm_package_ws_has_241560546_weekly_down_open_websocket_session", {"target_url": target_url, "headers": headers, "frame_schema_json": frame_schema_json, "connect_timeout_ms": connect_timeout_ms})


open_websocket_session_tool = StructuredTool.from_function(
    func=_open_websocket_session_impl,
    name="nexus_npm_package_ws_has_241560546_weekly_down_open_websocket_session",
    description='Establishes a persistent WebSocket connection to a target URL and registers it in the stateful session registry. Returns a session_id for all subsequent operations. Use when an agent needs to initiate a long-lived connection before sending or receiving frames. Do NOT use to reconnect an already-open session — call close_websocket_session first, or use the session_id of an existing session.',
    args_schema=OpenWebsocketSessionInput,
)

class SendTypedWsFrameInput(BaseModel):
    session_id: str = Field(..., description='UUID of an open session returned by open_websocket_session.')
    payload: str = Field(..., description="Frame payload. For binary frames, encode as Base64 and set frame_type to 'binary'.")
    frame_type: str = Field(None, description="Either 'text' or 'binary'. Determines wire encoding. Default is 'text'.")


def _send_typed_ws_frame_impl(session_id, payload, frame_type) -> Any:
    return call_mcp_tool("nexus_npm_package_ws_has_241560546_weekly_down_send_typed_ws_frame", {"session_id": session_id, "payload": payload, "frame_type": frame_type})


send_typed_ws_frame_tool = StructuredTool.from_function(
    func=_send_typed_ws_frame_impl,
    name="nexus_npm_package_ws_has_241560546_weekly_down_send_typed_ws_frame",
    description="Sends a single text or binary frame over an open session and returns the frame's Shannon entropy delta relative to the session baseline — confirming delivery and quantifying how novel this frame is versus the established message distribution. Use for request-response patterns or publishing commands to a WebSocket server. Do NOT use to send a sequence of frames in bulk — call this tool once per frame to preserve per-frame entropy tracking. Fails if session_id does not exist or connection is not in OPEN state.",
    args_schema=SendTypedWsFrameInput,
)

class DrainWsFrameBufferInput(BaseModel):
    session_id: str = Field(..., description='UUID of the open session to drain frames from.')
    max_frames: float = Field(None, description='Maximum number of buffered frames to return in a single call. Frames are returned in arrival order (FIFO). Remaining frames stay in buffer.')
    entropy_anomaly_threshold: float = Field(None, description='If set, only return frames whose absolute Shannon entropy delta exceeds this threshold (bits). Use to surface only anomalous frames. Set to 0 or omit to return all frames.')


def _drain_ws_frame_buffer_impl(session_id, max_frames, entropy_anomaly_threshold) -> Any:
    return call_mcp_tool("nexus_npm_package_ws_has_241560546_weekly_down_drain_ws_frame_buffer", {"session_id": session_id, "max_frames": max_frames, "entropy_anomaly_threshold": entropy_anomaly_threshold})


drain_ws_frame_buffer_tool = StructuredTool.from_function(
    func=_drain_ws_frame_buffer_impl,
    name="nexus_npm_package_ws_has_241560546_weekly_down_drain_ws_frame_buffer",
    description='Returns up to `max_frames` buffered inbound frames received since the last drain (or session open), each annotated with its Shannon entropy delta and schema validation result. Use to poll for incoming messages without holding a blocking connection. Do NOT use as a real-time streaming mechanism — it returns only frames already buffered; for high-frequency streams increase poll cadence or reduce max_frames. Returns empty list if no frames have arrived since last call.',
    args_schema=DrainWsFrameBufferInput,
)

class InspectWsSessionTelemetryInput(BaseModel):
    session_id: str = Field(..., description='UUID of the session to inspect.')
    entropy_window_frames: float = Field(None, description='Number of most-recent frames to include in the rolling entropy window calculation. Larger windows give more stable estimates; smaller windows are more sensitive to recent drift.')


def _inspect_ws_session_telemetry_impl(session_id, entropy_window_frames) -> Any:
    return call_mcp_tool("nexus_npm_package_ws_has_241560546_weekly_down_inspect_ws_session_telemetry", {"session_id": session_id, "entropy_window_frames": entropy_window_frames})


inspect_ws_session_telemetry_tool = StructuredTool.from_function(
    func=_inspect_ws_session_telemetry_impl,
    name="nexus_npm_package_ws_has_241560546_weekly_down_inspect_ws_session_telemetry",
    description='Returns real-time telemetry for a session: connection state, frame counts (sent/received), cumulative and rolling Shannon entropy statistics, schema violation rate, and uptime. Use to diagnose whether a stream is diverging from its expected schema or to verify a session is still alive before sending. Do NOT use as the primary liveness check in a tight loop — it performs entropy aggregation on each call; poll at most once per second.',
    args_schema=InspectWsSessionTelemetryInput,
)

class CloseWebsocketSessionInput(BaseModel):
    session_id: str = Field(..., description='UUID of the session to close.')
    close_code: float = Field(None, description='WebSocket close status code per RFC 6455. Standard values: 1000 (normal closure), 1001 (going away), 1008 (policy violation). Defaults to 1000.')
    close_reason: str = Field(None, description='Optional UTF-8 close reason string sent in the close frame. Must be 123 bytes or fewer per RFC 6455.')
    drain_before_close: bool = Field(None, description='If true, all buffered inbound frames are included in the final telemetry snapshot before the session is destroyed. If false, buffered frames are discarded immediately.')


def _close_websocket_session_impl(session_id, close_code, close_reason, drain_before_close) -> Any:
    return call_mcp_tool("nexus_npm_package_ws_has_241560546_weekly_down_close_websocket_session", {"session_id": session_id, "close_code": close_code, "close_reason": close_reason, "drain_before_close": drain_before_close})


close_websocket_session_tool = StructuredTool.from_function(
    func=_close_websocket_session_impl,
    name="nexus_npm_package_ws_has_241560546_weekly_down_close_websocket_session",
    description='Sends a WebSocket close frame with the specified status code, waits for the server close handshake, and removes the session from the registry. Returns a final telemetry snapshot including total frames exchanged and terminal entropy statistics. Use when a session is no longer needed or before re-opening a connection to the same URL. Do NOT use to temporarily pause a session — the session_id is permanently deallocated after this call and cannot be reused.',
    args_schema=CloseWebsocketSessionInput,
)